### PR TITLE
fix: Failed to encrypt the data with the generated key. #35

### PR DESCRIPTION
**Pull request by blacktiago**
Applying this solution 
https://stackoverflow.com/a/44900204/11914568
to the scenario described at https://github.com/appcelerator-modules/titanium-identity/issues/35

### CODE REVIEW

**Comment by ewanharris** [comment]
@blacktiago, I cherry-picked your commit into a new branch, fixed the merge conflicts and opened a new PR at #59

**Comment by blacktiago** [comment]
@ewanharris  thank you so much, I'm very happy and proud that it is finally going to production

**Comment by ewanharris** [comment]
@blacktiago, thank you for the contribution! Before we can merge that PR could I make sure that you've signed the CLA at https://cla.axway.com/

**Comment by blacktiago** [comment]
Thank you @ewanharris It's done, I've already signed it

**Pull request closed without merging**
